project:
  type: book
  output-dir: _out

book:
  title: "Facharbeit"
  author: "Simon Sommer"
  date: "02/10/2022"
  date-format: DD.MM.YYYY
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - data_types.qmd
    - references.qmd

bibliography: cite/references.bib
csl: cite/bszbt.csl

crossref:
  fig-title: Abb. # (default is "Figure")
  # tbl-title: (default is "Table")
  # title-delim: (default is ":")

toc: true
toc-title: Contents
number-sections: true

# https://quarto.org/docs/reference/formats/pdf.html#fonts
sansfont: "Arial Nerd Font"
mainfont: "Arial Nerd Font"
monofont: "FiraCode Nerd Font"
linestretch: 1.5
# code-line-numbers: true

# filters:
#   - "customize/test.lua"

format:
  html:
    theme:
      light: lightly
      dark: darkly
    code-copy: true
    page-navigation: true
  pdf:
    pdf-engine: xelatex
    documentclass: book
    papersize: a4
    fontsize: "11"

geometry:
  # - showframe
  - top=20mm
  - bottom=20mm
  - left=25mm
  - right=20mm
