project:
  type: book
  output-dir: _out
  resources: data

book:
  title: "Facharbeit"
  # author: "Simon Sommer"
  # date: "02/10/2023"
  date-format: DD.MM.YYYY
  chapters:
    - index.qmd
    - chapters/characteristics.qmd
    - chapters/analysis.qmd
    # - chapters/analysis_de.qmd
    - chapters/syntax.qmd
    - chapters/variables.qmd
    - chapters/primitive_data_types.qmd
    - chapters/algebraic_data_types.qmd
    - chapters/function.qmd
    - chapters/polymorphism.qmd
    - chapters/tooling_ecosystem.qmd
    - chapters/conclusion.qmd
    - chapters/appendix.qmd
    - chapters/references.qmd
lang: "de-DE"
filters:
  - quarto
  - custom/quote.lua

bibliography:
  - cite/general.bib
  - cite/literature.bib
  - cite/standards.bib
csl: custom/ieee.csl
# crossref:
#   fig-title: Abbildung # (default is "Figure")
#   tbl-title: Tabelle # (default is "Table")
#   # title-delim: (default is ":")

toc: true
toc-depth: 2
number-sections: true

# https://quarto.org/docs/reference/formats/pdf.html#fonts
sansfont: "Arial Nerd Font"
mainfont: "Arial Nerd Font"
monofont: "FiraCode Nerd Font"
linestretch: 1.5

code-block-border-left: true
syntax-definitions: [custom/rym.xml]
highlight-style:
  light: custom/light.theme # github, kate, printing, tango
  dark: custom/dark.theme # dracula, github

format:
  html:
    theme:
      light: lightly
      dark: darkly
    code-copy: true
    page-navigation: true
    code-fold: true
  docx:
    reference-doc: custom/reference-doc.docx
