project:
  type: book
  output-dir: _out

book:
  title: "Facharbeit"
  author: "Simon Sommer"
  date: "02/10/2022"
  date-format: DD.MM.YYYY
  chapters:
    - index.qmd
    - primitive_data_types.qmd
    - algebraic_data_types.qmd
    - tooling_ecosystem.qmd
    - references.qmd

lang: "en-GB"
bibliography: cite/references.bib
csl: cite/bszbt.csl

crossref:
  fig-title: Abb. # (default is "Figure")
  tbl-title: Tabelle # (default is "Table")
  # title-delim: (default is ":")

toc: true
toc-title: Contents
number-sections: true

# https://quarto.org/docs/reference/formats/pdf.html#fonts
sansfont: "Arial Nerd Font"
mainfont: "Arial Nerd Font"
monofont: "FiraCode Nerd Font"
linestretch: 1.5
highlight-style: github # dracula, github
code-block-border-left: true

format:
  html:
    theme:
      light: lightly
      dark: darkly
    code-copy: true
    page-navigation: true
    code-fold: true
  docx:
    highlight-style: tango # github, kate, printing, tango
    reference-doc: custom/reference-doc.docx
  # pdf:
  #   pdf-engine: xelatex
  #   documentclass: nostarch
  #   papersize: a4
  #   # format-resources:
  #   # - customize/custom.cls
  #   fontsize: "11"
# geometry:
#   - showframe
#   - top=20mm
#   - bottom=20mm
#   - left=25mm
#   - right=20mm
