project:
  type: book
  output-dir: _out

book:
  title: "Facharbeit"
  author: "Simon Sommer"
  date: "02/10/2022"
  date-format: DD.MM.YYYY
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: cite/references.bib
csl: cite/bszbt.csl

crossref:
  fig-title: Abb. # (default is "Figure")
  # tbl-title: (default is "Table")
  # title-delim: (default is ":")

toc: true
toc-title: Contents
number-sections: true

mainfont: "Arial"
monofont: "FiraCode Nerd Font"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    page-navigation: true
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    papersize: a4

geometry:
  # - showframe
  - top=20mm
  - bottom=20mm
  - left=25mm
  - right=20mm
