project:
  type: book
  output-dir: _out

book:
  title: "Facharbeit"
  author: "Simon Sommer"
  date: "02/10/2022"
  date-format: DD.MM.YYYY
  chapters:
    - index.qmd
    - general_trends.qmd
    - function.qmd
    - polymorphism.qmd
    - primitive_data_types.qmd
    - algebraic_data_types.qmd
    - tooling_ecosystem.qmd
    - appendix.qmd
    - references.qmd

lang: "de-DE"
filters:
  - quarto
  - custom/quote.lua

bibliography: cite/references.bib
csl: cite/bszbt.csl
crossref:
  fig-title: Abb. # (default is "Figure")
  tbl-title: Tabelle # (default is "Table")
  # title-delim: (default is ":")

toc: true
number-sections: true

# https://quarto.org/docs/reference/formats/pdf.html#fonts
sansfont: "Arial Nerd Font"
mainfont: "Arial Nerd Font"
monofont: "FiraCode Nerd Font"
linestretch: 1.5

code-block-border-left: true
syntax-definitions: [custom/rym.xml]
highlight-style:
  light: custom/light.theme # github, kate, printing, tango
  dark: custom/dark.theme # dracula, github

format:
  html:
    theme:
      light: lightly
      dark: darkly
    code-copy: true
    page-navigation: true
    code-fold: true
  docx:
    reference-doc: custom/reference-doc.docx
